---
driver:
  name: vagrant
  synced_folders:
  - ['~/chef-kits', '/mnt/share', 'disabled: false']

provisioner:
  name: chef_zero
  #require_chef_omnibus: 12.4.1
  #chef_omnibus_url: file:///mnt/share/install_chef_rpm.sh
  client_rb:
    # Use :enabled, :disabled or :audit_only to run the ServerSpec tests in the recipes
    audit_mode: :disabled

platforms:
  - name: centos-7.1
  - name: centos-6.7
  #- name: ubuntu-14.04

suites:
  - name: default
    driver:
      network:
        - ["private_network", {ip: "192.168.56.81"}]
    run_list:
      - recipe[compliance::genkey]
      - recipe[compliance::default]
    attributes:

  - name: node01
    driver:
      network:
        - ["private_network", {ip: "192.168.56.82"}]
    run_list:
      #- recipe[compliance::default]
      - recipe[compliance::authorize_key]

    attributes:
